{{- $imagePullSecrets := .Values.image.pullSecrets -}}

{{- range .Values.jobs }}
---
apiVersion: batch/v1
kind: Job
metadata:
{{- if .useGenerateName }}
  generateName: "{{ .name }}-"
{{- else }}
  name: {{ .name }}
{{- end }}
{{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  template:
    spec:
      containers:
      - name: {{ .name }}
        {{- if and (.image).tag .image.repository }}
        image: "{{ .image.repository }}:{{ .image.tag }}"
        {{- else }}
        image: {{ include "common.image" $ }}
        {{- end }}
        imagePullPolicy: {{ .imagePullPolicy | default "IfNotPresent"}}
        {{- with .resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .command }}
        command:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .args }}
        args:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .env }}
        env:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .envFrom }}
        envFrom:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .volumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- if .imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .imagePullSecrets | nindent 6 }}
      {{- else }}
      {{- with $imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- end }}
      restartPolicy: {{ .restartPolicy | default "OnFailure" }}
      {{- with .podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .volumes }}
      volumes:
        {{- toYaml . | nindent 6 }}
    {{- end }}

      terminationGracePeriodSeconds: {{ .terminationGracePeriodSeconds | default 30 }}
  backoffLimit: {{ .backoffLimit | default 6 }}
{{- end }}
