{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- if .Values.networkPolicy.ingress.enabled }}
    - Ingress
    {{- end }}
    {{- if .Values.networkPolicy.egress.enabled }}
    - Egress
    {{- end }}
  {{- if .Values.networkPolicy.ingress.enabled }}
  ingress:
    {{- toYaml .Values.networkPolicy.ingress.content | nindent 4 }}
  {{- end }}
  {{- if .Values.networkPolicy.egress.enabled }}
  egress:
    {{- toYaml .Values.networkPolicy.egress.content | nindent 4 }}
  {{- end }}
{{- end }}
