apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClasses.gp3.name }}
  labels:
    {{- include "aws-ebs-storage-classes.labels" . | nindent 4 }}
spec:
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  fsType: ext4
volumeBindingMode: {{ .Values.storageClasses.gp3.volumeBindingMode }}
